export const scenarios = {
  safe: {
    id: "safe",
    marketMode: "live",
    title: "Disciplined BNB entry",
    subtitle: "A measured position inside every mandate limit",
    symbol: "BNBUSDT",
    side: "BUY",
    portfolioValue: 10000,
    currentAssetValue: 1000,
    orderValue: 500,
    stopDistancePercent: 2,
    spreadBps: 4.2,
    volatilityPercent: 2.1,
    dailyQuoteVolume: 420000000,
    prompt: "Buy $500 of BNB, but never risk more than 1% of my portfolio.",
  },
  risky: {
    id: "risky",
    marketMode: "live",
    title: "Concentrated high-risk order",
    subtitle: "The agent refuses and proposes a safer size",
    symbol: "BNBUSDT",
    side: "BUY",
    portfolioValue: 10000,
    currentAssetValue: 1000,
    orderValue: 5000,
    stopDistancePercent: 8,
    spreadBps: 6.8,
    volatilityPercent: 3.4,
    dailyQuoteVolume: 420000000,
    prompt: "Put $5,000 into BNB now. Use an 8% stop.",
  },
  volatility: {
    id: "volatility",
    marketMode: "stress",
    title: "Volatility circuit breaker",
    subtitle: "A valid order is cancelled when conditions change",
    symbol: "BTCUSDT",
    side: "BUY",
    portfolioValue: 20000,
    currentAssetValue: 2000,
    orderValue: 800,
    stopDistancePercent: 2.5,
    spreadBps: 11,
    volatilityPercent: 9.2,
    dailyQuoteVolume: 1800000000,
    prompt: "Buy $800 of BTC if the risk mandate still permits it.",
  },
};
